name: Docker Image CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.GCP_PROJECT_ID }}/basic-nginx
  IMAGE_TAG: ${{ github.run_number }}
  INSTANCE_GROUP_NAME: basic-nginx-${{ github.run_number }}
  INSTANCE_TEMPLATE_NAME: basic-nginx-${{ github.run_number }}

jobs:

  build-image:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: container-based

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure the Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Build Docker image
      run: |-
        docker build -f Dockerfile -t $IMAGE_NAME:latest .

    - name: Push Docker Image to Google Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$IMAGE_NAME:$IMAGE_TAG
        docker push gcr.io/$IMAGE_NAME:$IMAGE_TAG

  create-instance-template:

    runs-on: ubuntu-latest
    steps:

    - name: Create Instance Template
      run: |-
        gcloud compute instance-templates create-with-container $INSTANCE_TEMPLATE_NAME \
          --container-image gcr.io/$IMAGE_NAME:latest

  execute-mig-updater:

    runs-on: ubuntu-latest
    steps:

    - name: Update Managed Instance Group
      run: |-
        gcloud compute instance-groups managed rolling-action start-update $INSTANCE_GROUP_NAME \
          --version=template=$INSTANCE_TEMPLATE_NAME \
          --type=proactive
